/*************************************************************************
	> File Name: EP45.c
	> Author: luowen
	> Mail: PohZero_Luo@163.com
	> Created Time: Tue 01 Dec 2020 08:33:35 PM CST
 ************************************************************************/

/*
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 * Triangle Tn=n(n+1)/2     1,3,6,10,15,...
 * Pentagonal Pn=n(3n-1)/2  1,5,12,22,35,...
 * Hexagonal Hn=n(2n-1)     1,6,15,28,45,...
 * It can be verified that T285=P165=H143=40755.
 * Find the next triangle number that is also pentagonal and hexagonal.
 */

#include<stdio.h>
#include <inttypes.h>

int64_t Triangle(int64_t n) {
    return n * (n + 1) / 2;
}

int64_t Pentagonal(int64_t n) {
    return n * (3 * n - 1) / 2;
}

int64_t Hexagonal(int64_t n) {
    return n * (2 * n - 1);
}

// n:范围 x:被查找数
int64_t binary_search(int64_t (*num)(int64_t), int64_t n, int64_t x) {
    int64_t head = 0, tail = n - 1, mid;
    while (head <= tail) {
        mid = (head + tail) >> 1;
        if (num(mid) < 0) printf("erro\n");
        if (num(mid) == x) return mid;
        if (num(mid) < x) head = mid + 1;
        else tail = mid - 1;
    }
    return -1;
}

int main() {
    int64_t n = 285;
    while (1) {
        n++;
        int64_t val = Triangle(n);
        if (binary_search(Pentagonal, val, val) == -1 ) continue;
        if (binary_search(Hexagonal, val, val) == -1) continue;
        printf("%ld\n", val);
        break;
    }

    return 0;
}
